### ISSUE TITLE
500 Internal Server Error When hit oauth/token endpoint

### ISSUE THREAD

**Issue by madawei2699** [nicolaiarocci/flask-sentinel#9]
I install flask-sentinel and use the 
`curl -k -X POST -d "client_id=DN1KJb5kxpSUYxOSn8MZVLvXrtvPKjqqZ69GakjR&grant_type=password&username=test&password=test" https://127.0.0.1:5000/oauth/token` 
the username and password and client_id is created by the management, and the error is 
`The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.` 
Then I try the Postman tool, and the same error occured.
Please help me, Thanks a lot!

**Comment by dmazzer** [comment]
Hello, I'm facing the same problem.

This is the stack trace, with `DEBUG` enabled.

```
127.0.0.1 - - [07/May/2016 10:27:05] "POST /testauth/testtoken HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauthlib/provider/oauth2.py", line 489, in decorated
    uri, http_method, body, headers, credentials
  File "build/bdist.linux-x86_64/egg/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/oauthlib/oauth2/rfc6749/endpoints/token.py", line 100, in create_token_response
    request, self.default_token_type)
  File "build/bdist.linux-x86_64/egg/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 101, in create_token_response
    if not self.request_validator.authenticate_client(request):
  File "/usr/local/lib/python2.7/dist-packages/flask_oauthlib/provider/oauth2.py", line 607, in authenticate_client
    if client.client_secret != client_secret:
AttributeError: 'Client' object has no attribute 'client_secret'
```

Please, point me out where should I work on and I will try to fix this.
Thanks.

**Comment by bethnull** [comment]
Me too, exceptions.AttributeError: 'Client' object has no attribute 'client_secret', after debugging it a bit the retrieved client in oauth.py line 603 doesn't have the .client_secret attribute.

Any suggestion about how to fix that?

**Comment by madawei2699** [comment]
https://github.com/nicolaiarocci/flask-sentinel/pull/10
It can be fixed by this pull request.

**Comment by nicolaiarocci** [comment]
Hello folks, sorry I did not have the the time to check into this, but I plan on doing that soon! Hang in there!

**Comment by nicolaiarocci** [comment]
Ah I see, it happens with Flask-Oauthlib 0.9.2. That teaches me not pinning the requirements (works fine with 0.8.0)

**Comment by nicolaiarocci** [comment]
Actually, it also work with 0.9.1. Looks like they have a regression going on here, see https://github.com/lepture/flask-oauthlib/issues/246.

**Comment by nicolaiarocci** [comment]
I am going to pin 0.9.1 it is fixed upstream.

**Comment by nicolaiarocci** [comment]
Also see #5

**Comment by nicolaiarocci** [comment]
@lepture was really fast at looking into this. I just tested the now updated master branch of Flask-OAuthlib, and it is working fine. Next Flask-OAuthlib release will have the fix. Until then, just fallback to Flask-OAuthlib v0.9.1.

**Comment by bethnull** [comment]
Tested and works! Thanks guys for your support.

**Comment by nicolaiarocci** [comment]
FYI Flask-Sentinel 0.0.5 was released.

**Comment by ProvoK** [comment]
I'm still having the same error ( i dont know how to see the complete stack trace though).
